# Generated by Django 5.1 on 2024-08-27 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('symbol', models.CharField(max_length=5)),
                ('lastValue', models.FloatField()),
                ('datelastValue', models.DateTimeField(default=datetime.datetime.now)),
                ('supLimit', models.FloatField()),
                ('botLimit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TemporalSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('stockValue', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='stocks_check_period',
            new_name='stocksCheckPeriod',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='monitored_stocks',
        ),
        migrations.AddField(
            model_name='profile',
            name='monitoredStocks',
            field=models.ManyToManyField(to='users.stockmonitor'),
        ),
    ]
