# Generated by Django 5.1 on 2024-08-27 15:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_stockmonitor_temporalseries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('stockValue', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='TemporalSeries',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='monitoredStocks',
        ),
        migrations.AddField(
            model_name='stockmonitor',
            name='profile',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='stockMonitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.stockmonitor'),
        ),
    ]
