# Generated by Django 5.1 on 2024-08-29 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_record_delete_temporalseries_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='stocksCheckPeriod',
            new_name='monitoring_period',
        ),
    ]
