# Generated by Django 5.1 on 2024-09-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_stockscheckperiod_profile_monitoring_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selectedToken',
            field=models.CharField(default='PETR4', max_length=5),
        ),
    ]
