# Generated by Django 5.1 on 2024-09-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_selectedtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selectedToken',
            field=models.CharField(default='PETR4.SA', max_length=5),
        ),
    ]
