# Generated by Django 5.1 on 2024-09-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_selectedtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selectedToken',
            field=models.CharField(default='PETR4.SA', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmonitor',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='stockmonitor',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
    ]
