# Generated by Django 5.1 on 2024-09-10 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_selectedtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmonitor',
            name='lastValue',
        ),
    ]
