# Generated by Django 5.1 on 2024-09-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_stockmonitor_lastvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='alert',
            field=models.BooleanField(default=False),
        ),
    ]
